export const config = {
  runtime: 'edge',
}

export default async function handler(req: Request) {
  // Handle preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, {
      status: 204,
      headers: {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': 'POST, OPTIONS',
        'Access-Control-Allow-Headers': 'Content-Type, Authorization',
      },
    })
  }

  if (req.method !== 'POST') {
    return new Response(JSON.stringify({ error: 'Method not allowed' }), {
      status: 405,
      headers: {
        'Content-Type': 'application/json',
        'Access-Control-Allow-Origin': '*',
      },
    })
  }

  try {
    const { email, pdfBase64, company, totalSavings } = await req.json()

    if (!email || !pdfBase64 || !company) {
      return new Response(
        JSON.stringify({ error: 'Missing required parameters (email, pdfBase64, company)' }),
        {
          status: 400,
          headers: {
            'Content-Type': 'application/json',
            'Access-Control-Allow-Origin': '*',
          },
        }
      )
    }

    const resendApiKey = process.env.RESEND_API_KEY || process.env.VITE_RESEND_API_KEY
    if (!resendApiKey || resendApiKey === 'your-resend-api-key') {
      console.error('RESEND_API_KEY is not configured in Vercel environment')
      return new Response(
        JSON.stringify({ error: 'Email service is not configured. Please set RESEND_API_KEY.' }),
        {
          status: 500,
          headers: {
            'Content-Type': 'application/json',
            'Access-Control-Allow-Origin': '*',
          },
        }
      )
    }

    // Call Resend's API to send email with the PDF attachment
    const resendResponse = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${resendApiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        from: 'SpendSight AI <onboarding@resend.dev>', // Free tier default sandbox email
        to: email,
        subject: `Your SpendSight AI Audit Report - ${company}`,
        html: `
          <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 32px 24px; border: 1px solid #e2e8f0; border-radius: 24px; background-color: #ffffff; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.05);">
            <div style="text-align: center; margin-bottom: 32px;">
              <span style="font-size: 24px; font-weight: 800; letter-spacing: -0.5px; color: #4f46e5; background: linear-gradient(to right, #4f46e5, #d946ef); -webkit-background-clip: text; -webkit-text-fill-color: transparent;">SpendSight AI</span>
            </div>
            
            <h2 style="color: #0f172a; font-size: 22px; font-weight: 800; margin-top: 0; margin-bottom: 12px; letter-spacing: -0.5px;">Your Executive AI Spend Audit is Ready!</h2>
            <p style="color: #475569; font-size: 15px; line-height: 24px; margin-top: 0; margin-bottom: 24px;">Hello,</p>
            <p style="color: #475569; font-size: 15px; line-height: 24px; margin-top: 0; margin-bottom: 24px;">Thank you for using SpendSight AI! We have processed your AI stack and compiled a comprehensive audit report for <strong>${company}</strong>.</p>
            
            <div style="background: linear-gradient(135deg, #f4f4f5 0%, #e4e4e7 100%); padding: 24px; border-radius: 16px; margin: 24px 0; border-left: 4px solid #4f46e5;">
              <span style="font-size: 11px; font-weight: 800; color: #71717a; text-transform: uppercase; letter-spacing: 1px;">Estimated Monthly Savings</span>
              <h3 style="margin: 6px 0 0 0; font-size: 36px; font-weight: 900; color: #0f172a; letter-spacing: -1px;">$${Number(totalSavings).toFixed(0)}</h3>
            </div>
            
            <p style="color: #475569; font-size: 15px; line-height: 24px; margin-top: 0; margin-bottom: 24px;">We have generated and attached your premium <strong>PDF Audit Report</strong>. Inside you will find:</p>
            <ul style="color: #475569; font-size: 14px; line-height: 22px; margin-top: 0; margin-bottom: 24px; padding-left: 20px;">
              <li style="margin-bottom: 8px;">Specific tier consolidation & plan downgrades</li>
              <li style="margin-bottom: 8px;">Model caching & token-saving API strategies</li>
              <li style="margin-bottom: 8px;">Personalized executive recommendations generated by Google Gemini</li>
            </ul>
            
            <p style="color: #475569; font-size: 15px; line-height: 24px; margin-top: 0; margin-bottom: 24px;">To access your report digitally or share it with your team, you can visit the link anytime. If you have any questions or want assistance executing this cost optimization, reply directly to this email.</p>
            
            <hr style="border: 0; border-top: 1px solid #f1f5f9; margin: 32px 0;" />
            <p style="margin: 0; font-size: 13px; color: #94a3b8; line-height: 20px;">Best regards,<br><strong style="color: #64748b;">The SpendSight AI Team</strong></p>
          </div>
        `,
        attachments: [
          {
            filename: `SpendSight_AI_Audit_${company.replace(/[^a-zA-Z0-9]/g, '_')}.pdf`,
            content: pdfBase64,
          },
        ],
      }),
    })

    if (!resendResponse.ok) {
      const errorText = await resendResponse.text()
      console.error('Resend API call failed:', errorText)
      return new Response(
        JSON.stringify({ error: 'Failed to send email via Resend API: ' + errorText }),
        {
          status: 502,
          headers: {
            'Content-Type': 'application/json',
            'Access-Control-Allow-Origin': '*',
          },
        }
      )
    }

    return new Response(JSON.stringify({ success: true, message: 'Email sent successfully via Resend!' }), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
        'Access-Control-Allow-Origin': '*',
      },
    })
  } catch (error: unknown) {
    console.error('Internal server error in send-email Edge Function:', error)
    const err = error as Error
    return new Response(JSON.stringify({ error: err.message || 'Internal server error' }), {
      status: 500,
      headers: {
        'Content-Type': 'application/json',
        'Access-Control-Allow-Origin': '*',
      },
    })
  }
}
